name: Crear EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Esto permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4 # Actualizado a v4

    - name: Instalar Python
      uses: actions/setup-python@v5 # Actualizado a v5
      with:
        python-version: '3.10' 

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller Pillow

    - name: Crear EXE
      run: |
        # Si tienes icono usa: pyinstaller --noconsole --onefile --icon=icon.ico ip_finder.pyw
        pyinstaller --noconsole --onefile ip_finder.pyw

    - name: Subir el resultado
      uses: actions/upload-artifact@v4 # <--- AQUÍ ESTABA EL ERROR (Corregido a v4)
      with:
        name: IP-Finder-App
        path: dist/ip_finder.exe
        compression-level: 0 # Opcional: hace la subida más rápida
