name: Crear EXE 32-bits

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instalar Python 32-bits
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        architecture: 'x86' # <--- ESTO FUERZA LA VERSIÓN DE 32 BITS

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller Pillow

    - name: Crear EXE
      run: |
        # PyInstaller detectará automáticamente que el Python es de 32 bits
        # y creará un exe compatible con x86 (32 bits) y x64.
        pyinstaller --noconsole --onefile ip_finder.pyw

    - name: Subir el resultado
      uses: actions/upload-artifact@v4
      with:
        name: IP-Finder-32bit
        path: dist/ip_finder.exe
        compression-level: 0
